default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/priome-data.sqlite3

test:
  <<: *default
  database: db/priome-data.sqlite3

production:
  <<: *default
  database: db/priome-data.sqlite3
